"""add invoices and invoice_lines tables

Revision ID: 7009d77b4bf6
Revises: 5e2aa33a040b
Create Date: 2026-09-20 05:58:54.072001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7009d77b4bf6'
down_revision: Union[str, Sequence[str], None] = '5e2aa33a040b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
